# Optimized for Dell i7, 16GB RAM, 1TB SSD
system:
  max_workers: 4
  memory_limit: "12GB"
  gpu_enabled: false
  precision: "mixed"
  log_level: "INFO"
  cache_dir: "./cache"

trading:
  symbols_per_batch: 8
  update_interval: 300
  max_concurrent_pairs: 6
  confidence_threshold: 0.75
  risk_per_trade: 0.02
  max_daily_signals: 50
  enabled_markets:
    - "forex"
    - "crypto"

models:
  batch_size: 32
  model_parallelism: true
  cache_models: true
  quantization: true
  update_frequency: 86400
  ensemble_weights:
    deep_predictor: 0.25
    sentiment_analyzer: 0.15
    pattern_recognizer: 0.20
    risk_orchestrator: 0.15
    market_psychologist: 0.10
    quantum_analyzer: 0.15

data:
  cache_dir: "./data/cache"
  max_cache_size: "50GB"
  preload_data: true
  cleanup_interval: 3600
  sources:
    binance:
      enabled: true
      rate_limit: 10
    alphavantage:
      enabled: false
      api_key: ""

performance:
  use_async: true
  max_pending_tasks: 10
  timeout: 30
  monitoring_interval: 60
  health_check_interval: 300

telegram:
  bot_token: "YOUR_BOT_TOKEN"
  chat_id: "YOUR_CHAT_ID"
  enable_alerts: true
  alert_level: "info"
  batch_signals: true

security:
  encrypt_signals: true
  rate_limiting: true
  max_requests_per_minute: 30
  api_timeout: 10

logging:
  level: "INFO"
  file: "./logs/trading_system.log"
  max_size: "10MB"
  backup_count: 5
  enable_performance_logging: true
